# Generated by Django 5.2.1 on 2025-05-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelib_chiqishi', models.CharField(max_length=100, null=True)),
                ('absolutus', models.CharField(max_length=250)),
                ('soz_turkimi', models.CharField(verbose_name=100)),
                ('manosi', models.TextField()),
                ('misollar', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.omonim')),
            ],
        ),
    ]
