# Generated by Django 5.2.1 on 2025-06-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Omonim',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
